pipeline {
	agent any
	stages {
		stage('Install stage') {
			steps {
				dir("StockPricesApp") {
					bat 'mvn clean install'
				}
			}
		}
		stage('Docker') {
			steps {
				dir("StockPricesApp") {
					bat 'docker build -t toufiks/stockapp .'	
					bat 'docker run -d -p 9999:9090 --name stockapp_container toufiks/stockapp'
				}
			}
		}
		/*stage('Deploy stage') {
			steps {
				dir("StockPricesApp/target") {
					withEnv(['JENKINS_NODE_COOKIE=DontKillMe']) {
						bat 'start java -Dserver.port=3000 -jar StockPricesApp-0.0.1-SNAPSHOT.jar'
					}
				}
			}
		}*/
	}
}
