pipeline {
	agent any
	stages {
		stage('Install stage') {
			steps {
				dir("StockPricesApp") {
					bat 'mvn clean install'
				}
			}
		}
		stage('Stop Docker container if running') {
			steps {
				script {
					if (docker.containerExists(stockcontainer)) {
						docker.stop(stockcontainer)
					}else{
						println("Docker container does not exist")
					}
				}
			}
		}
		stage('Delete Docker image if exists') {
			steps {
				script {
					if (docker.imageExists(stockapp)) {
						docker.image(stockapp).remove()
					}else{
						println("Docker image does not exist")
					}
				}
			}
		}
		stage('Build Docker image') {
			steps {
				script {
					docker.build(stockapp, '.')
				}
			}
		}
		
		stage('Run Docker container') {
			steps {
				script {
					docker.run(
						stockapp,
						name: stockcontainer,
						rm: true,
						detach: true,
						ports: '9999:9090'
					)
				}
			}
		}
		/*stage('Deploy stage') {
			steps {
				dir("StockPricesApp/target") {
					withEnv(['JENKINS_NODE_COOKIE=DontKillMe']) {
						bat 'start java -Dserver.port=3000 -jar StockPricesApp-0.0.1-SNAPSHOT.jar'
					}
				}
			}
		}*/
	}
}
